- name: install tmux dependencies
  yum:
    name: [
      libevent-devel,
      ncurses-devel
    ]
    state: present

- name: delete tmux src archive
  file:
    path: /usr/local/src/tmux-2.8.tar.gz
    state: absent

- name: delete tmux src dir
  file:
    path: /usr/local/src/tmux-2.8
    state: absent

- name: unarchive tmux src
  unarchive:
    src: https://github.com/tmux/tmux/archive/2.8.tar.gz
    dest: /usr/local/src
    copy: no

- name: run autogen.sh
  shell: ./autogen.sh
  args:
    chdir: /usr/local/src/tmux-2.8

- name: configure tmux
  shell: ./configure
  args:
    chdir: /usr/local/src/tmux-2.8

- name: make all tmux
  make:
    chdir: /usr/local/src/tmux-2.8

- name: make install tmux
  make:
    chdir: /usr/local/src/tmux-2.8
    target: install
